# Generated by Django 5.2.1 on 2025-05-25 19:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("learners", "0002_prompt_response"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(old_name="Prompt", new_name="LearnerPrompt",),
    ]
