# Generated by Django 5.2.1 on 2025-05-29 14:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learners", "0003_rename_prompt_learnerprompt"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="learnerprompt", options={"ordering": ["-updated_at"]},
        ),
        migrations.AlterModelOptions(
            name="response", options={"ordering": ["created_at"]},
        ),
        migrations.AddField(
            model_name="learnerprompt",
            name="title",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="learnerprompt",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="response",
            name="role",
            field=models.CharField(
                choices=[("user", "User"), ("assistant", "Assistant")],
                default="assistant",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="learnerprompt",
            name="learner",
            field=models.ForeignKey(
                limit_choices_to={"role": "LEARNER"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="conversations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="response",
            name="prompt",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="learners.learnerprompt",
            ),
        ),
    ]
