# Generated by Django 5.2.1 on 2025-05-25 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_learnerprofile_grade_learnerprofile_parent_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="teacherprofile", name="user",),
        migrations.DeleteModel(name="ParentProfile",),
        migrations.DeleteModel(name="TeacherProfile",),
    ]
