# Generated by Django 5.2.1 on 2025-05-25 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_remove_teacherprofile_user_delete_parentprofile_and_more"),
    ]

    operations = [
        migrations.DeleteModel(name="LearnerProfile",),
    ]
