# Generated by Django 5.2.1 on 2024-05-24 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_gender_user_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='full_name',
        ),
    ] 