# Generated by Django 5.2.1 on 2025-05-31 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_remove_user_full_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="grade",
            field=models.CharField(
                blank=True,
                choices=[
                    ("1", "Grade 1"),
                    ("2", "Grade 2"),
                    ("3", "Grade 3"),
                    ("4", "Grade 4"),
                    ("5", "Grade 5"),
                    ("6", "Grade 6"),
                    ("7", "Grade 7"),
                    ("8", "Grade 8"),
                    ("9", "Grade 9"),
                    ("10", "Grade 10"),
                    ("11", "Grade 11"),
                    ("12", "Grade 12"),
                ],
                max_length=2,
            ),
        ),
    ]
